<?php
use App\Models\Champ;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('champs', function (Blueprint $table) {
            $table->id();
            $table->String('nev');
            $table->String('nem');
            $table->String('pozicio');
            $table->String('faj');
            $table->String('nyersanyag');
            $table->String('fegyver');
            $table->String('szarmazas');
            $table->integer('megjelenes');
            $table->timestamps();
        });
        Champ::create([
            'nev'=>'Darius',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Noxus',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Akali',
            'nem'=>'Nő',
            'pozicio'=>'Top/Mid',
            'faj'=>'Ember',
            'nyersanyag'=>'Energia',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Aurelion Sol',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Égi/Sárkány',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Runaterra/Targon',
            'megjelenes'=>2016,
        ]);
        Champ::create([
            'nev'=>'Camille',
            'nem'=>'Nő',
            'pozicio'=>'Top',
            'faj'=>'Cyborg/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Piltover',
            'megjelenes'=>2016,
        ]);
        Champ::create([
            'nev'=>'Kayn',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Darkin/Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia/Noxus/Runeterra/Shurima',
            'megjelenes'=>2017,
        ]);
        Champ::create([
            'nev'=>'Reksai',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel',
            'faj'=>'Void',
            'nyersanyag'=>'Düh',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Shurima/Void',
            'megjelenes'=>2014,
        ]);
        Champ::create([
            'nev'=>'Amumu',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Támogató',
            'faj'=>'Halott/Yordle',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Annie',
            'nem'=>'Nő',
            'pozicio'=>'Mid/Támogató',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Noxus/Runeterra',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Braum',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató',
            'faj'=>'Ember/Fagyszülött',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2014,
        ]);
        Champ::create([
            'nev'=>'Jarvan IV',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Demácia',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Le Blanc',
            'nem'=>'Nő',
            'pozicio'=>'Mid',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Noxus',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Nilah',
            'nem'=>'Nő',
            'pozicio'=>'Bot',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Bilgewater',
            'megjelenes'=>2022,
        ]);
        Champ::create([
            'nev'=>'Azir',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Isten-harcos',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2014,
        ]);
        Champ::create([
            'nev'=>'Fiddlesticks',
            'nem'=>'Más',
            'pozicio'=>'Dzsungel',
            'faj'=>'Démon/Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Runeterra',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Wukong',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Top',
            'faj'=>'Vastayan',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Runeterra',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Maokai',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Támogató',
            'faj'=>'Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Shadow Isles',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Riven',
            'nem'=>'Nő',
            'pozicio'=>'Top',
            'faj'=>'Ember',
            'nyersanyag'=>'manátlan',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia/Noxus',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Shyvana',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel',
            'faj'=>'Sárkány/Varázslatosan megváltozott',
            'nyersanyag'=>'düh',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Demácia',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Syndra',
            'nem'=>'Nő',
            'pozicio'=>'Mid',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Naafiri',
            'nem'=>'Nő',
            'pozicio'=>'Mid',
            'faj'=>'Darkin/kutya',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2023,
        ]);
        Champ::create([
            'nev'=>'Karthus',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Halott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Noxus/Shadow Isles',
            'megjelenes'=>2023,
        ]);
        Champ::create([
            'nev'=>'Xayah',
            'nem'=>'Nő',
            'pozicio'=>'Bot',
            'faj'=>'Vastayan',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2017,
        ]);
        Champ::create([
            'nev'=>'Blitzcrank',
            'nem'=>'Más',
            'pozicio'=>'Támogató',
            'faj'=>'Gólem',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Zaun',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Graves',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Bilgewater',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Zilean',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Icathia/Runaterra/Shurima',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Evelynn',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel',
            'faj'=>'Démon/Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Runeterra',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Vex',
            'nem'=>'Nő',
            'pozicio'=>'Mid',
            'faj'=>'Yordle',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Bandle Város/Shadow Isles',
            'megjelenes'=>2021,
        ]);
        Champ::create([
            'nev'=>'Zed',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'Energia',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Olaf',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Top',
            'faj'=>'Ember/Fagyszülött',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'GangPlank',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Bilgewater',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Taliyah',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel/Mid',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2016,
        ]);
        Champ::create([
            'nev'=>'Yuumi',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Macska/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Bandle Város',
            'megjelenes'=>2019,
        ]);
        Champ::create([
            'nev'=>'Kindred',
            'nem'=>'Más',
            'pozicio'=>'Dzsungel',
            'faj'=>'Isten/Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Runeterra',
            'megjelenes'=>2015,
        ]);
        Champ::create([
            'nev'=>'Belvet',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel',
            'faj'=>'Void ',
            'nyersanyag'=>'manátlan',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Void',
            'megjelenes'=>2022,
        ]);
        Champ::create([
            'nev'=>'Veigar',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Yordle',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Bandle Város/Runeterra',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Sylas',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Demácia/Freljord',
            'megjelenes'=>2019,
        ]);
        Champ::create([
            'nev'=>'Miss Fortune',
            'nem'=>'Nő',
            'pozicio'=>'Bot',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Bilgewater',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Milio',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Ixtal',
            'megjelenes'=>2023,
        ]);
        Champ::create([
            'nev'=>'Ezreal',
            'nem'=>'Férfi',
            'pozicio'=>'Bot',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Piltover',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Tristana',
            'nem'=>'Nő',
            'pozicio'=>'Bot',
            'faj'=>'Yordle',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Bandle Város',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Elise',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos/Távolharcos',
            'szarmazas'=>'Noxus/Shadow Isles',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Poppy',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel/Top',
            'faj'=>'Yordle',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Demácia',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Kassadin',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Macska/Void',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Shurima/Void',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Ahri',
            'nem'=>'Nő',
            'pozicio'=>'Mid',
            'faj'=>'Vastayan',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Mordekaiser',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Revenant',
            'nyersanyag'=>'pajzs',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Noxus',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Aatrox',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Darkin',
            'nyersanyag'=>'manátlan',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Runeterra/Shurima',
            'megjelenes'=>2013,
        ]);
        Champ::create([
            'nev'=>'Valrus',
            'nem'=>'Férfi',
            'pozicio'=>'Bot/Mid',
            'faj'=>'Darkin/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Ionia/Runeterra/Shurima',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Quiyana',
            'nem'=>'Nő',
            'pozicio'=>'mid',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ixtal',
            'megjelenes'=>2019,
        ]);
        Champ::create([
            'nev'=>'Rakan',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató',
            'faj'=>'Vastayan',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2017,
        ]);
        Champ::create([
            'nev'=>'Galio',
            'nem'=>'Férfi',
            'pozicio'=>'Mid/Támogató',
            'faj'=>'Gólem',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Demácia',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Xerath',
            'nem'=>'Férfi',
            'pozicio'=>'Mid/Támogató',
            'faj'=>'Isten-harcos',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Diana',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel/Mid',
            'faj'=>'Aspect/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Targon',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Vi',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Piltover/Zaun',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Vayne',
            'nem'=>'Nő',
            'pozicio'=>'Bot/Top',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Demácia',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Khazix',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Void',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Void',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Ornn',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'God/Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2017,
        ]);
        Champ::create([
            'nev'=>'Draven',
            'nem'=>'Férfi',
            'pozicio'=>'Bot',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Noxus',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Quinn',
            'nem'=>'Nő',
            'pozicio'=>'Top',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Demácia',
            'megjelenes'=>2013,
        ]);
        Champ::create([
            'nev'=>'Akshan',
            'nem'=>'Férfi',
            'pozicio'=>'Mid/Top',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2021,
        ]);
        Champ::create([
            'nev'=>'Chogath',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Void',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Void',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Lillia',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel',
            'faj'=>'Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2020,
        ]);
        Champ::create([
            'nev'=>'Twitch',
            'nem'=>'Férfi',
            'pozicio'=>'Bot',
            'faj'=>'Kémiailag megváltozott/Patkány',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Zaun',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Ziggs',
            'nem'=>'Férfi',
            'pozicio'=>'Bot/Mid',
            'faj'=>'Yordle',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Zaun',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Gragas',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Top',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Zac',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Gólem',
            'nyersanyag'=>'Élet',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Zaun',
            'megjelenes'=>2013,
        ]);
        Champ::create([
            'nev'=>'Sivir',
            'nem'=>'Nő',
            'pozicio'=>'Bot',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Sona',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Demácia/Ionia',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Zeri',
            'nem'=>'Nő',
            'pozicio'=>'Bot',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Zaun',
            'megjelenes'=>2022,
        ]);
        Champ::create([
            'nev'=>'Viego',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Halott',
            'nyersanyag'=>'manátlan',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Camavor/Shadow Isles',
            'megjelenes'=>2021,
        ]);
        Champ::create([
            'nev'=>'Udyr',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Top',
            'faj'=>'Ember/Spirituális',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Freljord/Ionia',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Yone',
            'nem'=>'Férfi',
            'pozicio'=>'Mid/Top',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'manátlan',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2020,
        ]);
        Champ::create([
            'nev'=>'Caitlyn',
            'nem'=>'Nő',
            'pozicio'=>'Bot',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Piltover',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Cassiopeia',
            'nem'=>'Nő',
            'pozicio'=>'Mid',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Noxus/Shurima',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Malzahar',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Ember/Void',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Shurima/Void',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Tryndamere',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'düh',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Anivia',
            'nem'=>'Nő',
            'pozicio'=>'Mid',
            'faj'=>'God/Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Aphelios',
            'nem'=>'Férfi',
            'pozicio'=>'Bot',
            'faj'=>'Ember/Spirituális',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Targon',
            'megjelenes'=>2019,
        ]);
        Champ::create([
            'nev'=>'Lux',
            'nem'=>'Nő',
            'pozicio'=>'Mid/Támogató',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Demácia',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Corki',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Yordle',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Bandle Város/Piltover',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Ryzre',
            'nem'=>'Férfi',
            'pozicio'=>'Mid/Top',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Runeterra',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'KSante',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2022,
        ]);
        Champ::create([
            'nev'=>'Zoe',
            'nem'=>'Nő',
            'pozicio'=>'Mid',
            'faj'=>'Aspect/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Targon',
            'megjelenes'=>2017,
        ]);
        Champ::create([
            'nev'=>'Shen',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Ember/Spirituális',
            'nyersanyag'=>'Energia',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Fizz',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Yordle',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Bilgewater',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Ivern',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Freljord/Ionia',
            'megjelenes'=>2016,
        ]);
        Champ::create([
            'nev'=>'Kalista',
            'nem'=>'Nő',
            'pozicio'=>'Bot',
            'faj'=>'Halott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Camavor/Shadow Isles',
            'megjelenes'=>2014,
        ]);
        Champ::create([
            'nev'=>'Rengar',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Top',
            'faj'=>'Vastayan',
            'nyersanyag'=>'Vadság',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ixtal/Shurima',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Soraka',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Égi',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Ionia/Targon',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Kaisa',
            'nem'=>'Nő',
            'pozicio'=>'Bot',
            'faj'=>'Ember/Void',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Shurima/Void',
            'megjelenes'=>2018,
        ]);
        Champ::create([
            'nev'=>'Neeko',
            'nem'=>'Nő',
            'pozicio'=>'Mid/Támogató',
            'faj'=>'Vastayan',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Ixtal',
            'megjelenes'=>2018,
        ]);
        Champ::create([
            'nev'=>'Irelia',
            'nem'=>'Nő',
            'pozicio'=>'Mid/Top',
            'faj'=>'Ember/Spirituális',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Fiora',
            'nem'=>'Nő',
            'pozicio'=>'Top',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Demácia',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Sejuani',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel',
            'faj'=>'Ember/Fagyszülött',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Janna',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Isten/Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Shurima/Zaun',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Alistar',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató',
            'faj'=>'Minotaurusz',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Runeterra',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Urgot',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Kémiailag megváltozott/Cyborg/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Noxus/Zaun',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Nunu&Willump',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Ember/Yeti',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Lulu',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Yordle',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Bandle Város',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Seraphine',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Piltover/Zaun',
            'megjelenes'=>2020,
        ]);
        Champ::create([
            'nev'=>'Talon',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Mid',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Noxus',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Warwick',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Top',
            'faj'=>'Kémiailag megváltozott/Cyborg/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Zaun',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Illaoi',
            'nem'=>'Nő',
            'pozicio'=>'Top',
            'faj'=>'Ember/Spirituális',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Bilgewater',
            'megjelenes'=>2015,
        ]);
        Champ::create([
            'nev'=>'Pantheon',
            'nem'=>'Férfi',
            'pozicio'=>'Mid/Támogató/Top',
            'faj'=>'Aspect/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Targon',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Brand',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Freljord/Runeterra',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Nautilus',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató',
            'faj'=>'Revenant',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Bilgewater',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Jax',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Top',
            'faj'=>'Ismeretlen',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Icathia/Runeterra/Shurima',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Thresh',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató',
            'faj'=>'Halott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Shadow Isles',
            'megjelenes'=>2013,
        ]);
        Champ::create([
            'nev'=>'Kogmaw',
            'nem'=>'Férfi',
            'pozicio'=>'Bot',
            'faj'=>'Void',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Void',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Nami',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Vastayan',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Runeterra',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Nocturne',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Démon/Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Runeterra',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Leona',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Aspect/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Targon',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Katarina',
            'nem'=>'Nő',
            'pozicio'=>'Mid',
            'faj'=>'Ember',
            'nyersanyag'=>'manátlan',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Noxus',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Bard',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató',
            'faj'=>'Égi',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Runeterra',
            'megjelenes'=>2015,
        ]);
        Champ::create([
            'nev'=>'Tahm Kench',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató/Top',
            'faj'=>'Démon/Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Bilgewater/Runeterra',
            'megjelenes'=>2015,
        ]);
        Champ::create([
            'nev'=>'Garen',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Ember',
            'nyersanyag'=>'manátlan',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Demácia',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Kennen',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Yordle',
            'nyersanyag'=>'Energia',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Swain',
            'nem'=>'Férfi',
            'pozicio'=>'Mid/Támogató',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Noxus',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Lissandra',
            'nem'=>'Nő',
            'pozicio'=>'Mid',
            'faj'=>'Ember/Fagyszülött',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2013,
        ]);
        Champ::create([
            'nev'=>'Trundle',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Top',
            'faj'=>'Fagyszülött/Troll',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Lee Sin',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Ember/Spirituális',
            'nyersanyag'=>'Energia',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Renata Glasc',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Kémiailag megváltozott/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Zaun',
            'megjelenes'=>2022,
        ]);
        Champ::create([
            'nev'=>'Kayle',
            'nem'=>'Nő',
            'pozicio'=>'Top',
            'faj'=>'Aspect/Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos/Távolharcos',
            'szarmazas'=>'Demácia/Targon',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Jinx',
            'nem'=>'Nő',
            'pozicio'=>'Bot',
            'faj'=>'Kémiailag megváltozott/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Zaun',
            'megjelenes'=>2013,
        ]);
        Champ::create([
            'nev'=>'Morgana',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Aspect/Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Demácia/Targon',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Gwen',
            'nem'=>'Nő',
            'pozicio'=>'Top',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Camavor=Shadow Isles',
            'megjelenes'=>2021,
        ]);
        Champ::create([
            'nev'=>'Gnar',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Yordle',
            'nyersanyag'=>'düh',
            'fegyver'=>'Közelharcos/Távolharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2014,
        ]);
        Champ::create([
            'nev'=>'Skarner',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Brackern',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Nidalee',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel',
            'faj'=>'Ember/Spirituális',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos/Távolharcos',
            'szarmazas'=>'Ixtal',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Lucian',
            'nem'=>'Férfi',
            'pozicio'=>'Bot',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Demácia/Shadow Isles',
            'megjelenes'=>2013,
        ]);
        Champ::create([
            'nev'=>'Heimerdinger',
            'nem'=>'Férfi',
            'pozicio'=>'Mid/Támogató',
            'faj'=>'Yordle',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Piltover',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Jhin',
            'nem'=>'Férfi',
            'pozicio'=>'Bot',
            'faj'=>'Ember/Spirituális',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2016,
        ]);
        Champ::create([
            'nev'=>'Oriana',
            'nem'=>'Nő',
            'pozicio'=>'Mid',
            'faj'=>'Golem',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Piltover',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Dr.Mundo',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Kémiailag megváltozott/Ember',
            'nyersanyag'=>'Élet',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Zaun',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Rumble',
            'nem'=>'Férfi',
            'pozicio'=>'Mid/Top',
            'faj'=>'Yordle',
            'nyersanyag'=>'hő',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Bandle Város',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Ekko',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Mid',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Zaun',
            'megjelenes'=>2015,
        ]);
        Champ::create([
            'nev'=>'Briar',
            'nem'=>'Nő',
            'pozicio'=>'Dzsungel',
            'faj'=>'Golem',
            'nyersanyag'=>'Élet',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Noxus',
            'megjelenes'=>2023,
        ]);
        Champ::create([
            'nev'=>'Shaco',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Runeterra',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Viktor',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Cyborg/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Piltover/Zaun',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Senna',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Ember/Halott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Shadow Isles',
            'megjelenes'=>2019,
        ]);
        Champ::create([
            'nev'=>'Renekton',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Isten-harcos',
            'nyersanyag'=>'düh',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Jayce',
            'nem'=>'Férfi',
            'pozicio'=>'Mid/Top',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos/Távolharcos',
            'szarmazas'=>'Piltover',
            'megjelenes'=>2019,
        ]);
        Champ::create([
            'nev'=>'Teemo',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Yordle',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Bandle Város',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Ashe',
            'nem'=>'Nő',
            'pozicio'=>'Bot/Támogató',
            'faj'=>'Ember/Fagyszülött',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Karma',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Ember/Spirituális',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Hecarim',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Halott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Camavor/Shadow Isles',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Yasuo',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'Folyam',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2013,
        ]);
        Champ::create([
            'nev'=>'Volibear',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel/Top',
            'faj'=>'Isten/Spirit',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Freljord',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Nasus',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Isten-harcos',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Taric',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató',
            'faj'=>'Aspect/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Demácia/Targon',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Malphite',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Golem',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ixtal/Shurima',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Yorick',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Shadow Isles',
            'megjelenes'=>2011,
        ]);
        Champ::create([
            'nev'=>'Vladimir',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Ember/Varázslatosan megváltozott',
            'nyersanyag'=>'Vérszomj',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Camavor/Noxus/Shadow Isles',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Singed',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Kémiailag megváltozott/Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Piltover/Zaun',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Sion',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Revenant',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Noxus',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Xin Zhao',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Demácia/Ionia/Noxus',
            'megjelenes'=>2010,
        ]);
        Champ::create([
            'nev'=>'Rammus',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Isten-harcos',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Shurima',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Sett',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Ember/Vastayan',
            'nyersanyag'=>'Őrlemény',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2020,
        ]);
        Champ::create([
            'nev'=>'Pyke',
            'nem'=>'Férfi',
            'pozicio'=>'Támogató',
            'faj'=>'Revenant',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Bilgewater',
            'megjelenes'=>2018,
        ]);
        Champ::create([
            'nev'=>'Rell',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Ember/Varázslatosan megváltozott/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Noxus',
            'megjelenes'=>2020,
        ]);
        Champ::create([
            'nev'=>'Velkoz',
            'nem'=>'Férfi',
            'pozicio'=>'Mid/Támogató',
            'faj'=>'Void',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Void',
            'megjelenes'=>2014,
        ]);
        Champ::create([
            'nev'=>'Samira',
            'nem'=>'Nő',
            'pozicio'=>'Bot',
            'faj'=>'Ember',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Noxus/Shurima',
            'megjelenes'=>2020,
        ]);
        Champ::create([
            'nev'=>'Twisted Fate',
            'nem'=>'Férfi',
            'pozicio'=>'Mid',
            'faj'=>'Ember/Varázsló',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Bilgewater',
            'megjelenes'=>2009,
        ]);
        Champ::create([
            'nev'=>'Kled',
            'nem'=>'Férfi',
            'pozicio'=>'Top',
            'faj'=>'Yordle',
            'nyersanyag'=>'Bátorság',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Noxus',
            'megjelenes'=>2016,
        ]);
        Champ::create([
            'nev'=>'Zyra',
            'nem'=>'Nő',
            'pozicio'=>'Támogató',
            'faj'=>'Ismeretlen',
            'nyersanyag'=>'mana',
            'fegyver'=>'Távolharcos',
            'szarmazas'=>'Ixtal',
            'megjelenes'=>2012,
        ]);
        Champ::create([
            'nev'=>'Master Yi',
            'nem'=>'Férfi',
            'pozicio'=>'Dzsungel',
            'faj'=>'Ember/Spirituális',
            'nyersanyag'=>'mana',
            'fegyver'=>'Közelharcos',
            'szarmazas'=>'Ionia',
            'megjelenes'=>2009,
        ]);

    }
    

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('champs');
    }
};
